spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 778209
    url: jdbc:mysql://182.254.222.126:3306/sell?characterEncoding=utf-8
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 182.132.212.123
    port: 66080
server:
  context-path:  /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
## path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
##  level:
##    com.laohu.***
#  level: debug
wechat:
  mpAppId: 123456
  mpAppSecret: 123456
  openAppId: 1234546
  openAppSecret: 1234564
  mchId: 1409146202
  mchKey: c9654546545
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell*****/sell/pay/notify
  templateId:
        orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
projectUrl:
  wechatMpAuthorize: 1409146202
  wechatOpenAuthorize: 1409146202
  sell: 1409146202
logging:
  level:
    package com.laohu.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml

